
theme: jekyll-theme-cayman

title : Arnaud Becheler
description: PhD

author :
  name : Arnaud Becheler
  email : abechele@umich.edu
  github : becheler

google_analytics: UA-106771332-1

url: https://Becheler.github.io

mathjax: true

github: [metadata]

future: true

plugins:
  - jekyll-sitemap
