title: Arnaud Becheler - Personal website
description: > # this means to ignore newlines until "baseurl:"
  Arnaud Becheler's personal website, where I share about my research
  and about programming concept in a blog called Derek et Léonin.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: https://Becheler.github.io # the base hostname & protocol for your site, e.g. http://example.com

site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Arnaud Becheler # add your name
author-img: arnaud-becheler.png # add your photo
about-author: A French postdoctoral Researcher, always happy to learn about phylogeography and programming! # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-instagram: arnaud.becheler
social-github: Becheler  # add your Github handle
social-linkedin: linkedin.com/in/arnaud-becheler-246029172 # add your Linkedin handle
social-email: abechele@umich.edu # add your Email address

# Tracker
analytics: UA-106771332-1 # Google Analytics

# Collections directory
collections_dir: my_collections
collections:
  quetzal-coaltl-tutorials:
    output: true
    permalink: /software/quetzal-CoalTL/tutorials/:name
    order:
      - goals.md
      - getting-started.md
      - a-random-walker.md
      - many-lazy-walkers.md
      - geography.md
      - niche.md

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
